cookie:
  expiry_days: 7
  key: super_secret_key_change_me
  name: vacation_auth
credentials:
  usernames:
    demo:
      email: demo@example.com
      name: Demo User
      password: $2b$12$kEx1fGyPGyzgY9VhkIBIBuo66a8q8iw4XCW11ARgNn4R4aeSpS2qi
    lolas:
      email: ab@mail.com
      failed_login_attempts: 0
      first_name: Lola
      last_name: Arr
      logged_in: true
      password: $2b$12$bqjuDHgvX6jT7Ta12ZCy.eaF2wb2efB77n2IJS0PZDDxDRLpduzIy
      password_hint: dd
      roles: null
    moussa:
      email: moussa@example.com
      name: Moussa Salameh
      password: $2b$12$iz3KsYWpXDsWpONbvATOROo6scVgo1kEri1IB7icTcFYnR3TXrnBO
    Stephanie:
      email: stephanie@mail.com
      failed_login_attempts: 0
      first_name: Stephanie
      last_name: Salame
      logged_in: false
      password: $2b$12$2lzu0ecwn5W/wo1WW4JI6.SYcz47XTHMd7QVaZE2ICqttZPDoTzAK
      password_hint: kpkp
      roles: null
preauthorized:
  emails: []
